<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class WilayahSeeder extends Seeder
{
    /**
     * Run the datanggse seeds.
     */
    public function run(): void
    {
        DB::table('wilayah')->insert([
            // Data Provinsi Aceh (kode_prov = 11)
            ['kode_area' => '1101', 'nama_wilayah' => 'Kab. Simeulue', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1102', 'nama_wilayah' => 'Kab. Aceh Singkil', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1103', 'nama_wilayah' => 'Kab. Aceh Selatan', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1104', 'nama_wilayah' => 'Kab. Aceh Tenggara', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1105', 'nama_wilayah' => 'Kab. Aceh Timur', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1106', 'nama_wilayah' => 'Kab. Aceh Tengah', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1107', 'nama_wilayah' => 'Kab. Aceh Barat', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1108', 'nama_wilayah' => 'Kab. Aceh Besar', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1109', 'nama_wilayah' => 'Kab. Pidie', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1110', 'nama_wilayah' => 'Kab. Bireuen', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1111', 'nama_wilayah' => 'Kab. Aceh Utara', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1112', 'nama_wilayah' => 'Kab. Aceh Barat Daya', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1113', 'nama_wilayah' => 'Kab. Gayo Lues', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1114', 'nama_wilayah' => 'Kab. Aceh Tamiang', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1115', 'nama_wilayah' => 'Kab. Nagan Raya', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1116', 'nama_wilayah' => 'Kab. Aceh Jaya', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1117', 'nama_wilayah' => 'Kab. Bener Meriah', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1118', 'nama_wilayah' => 'Kab. Pidie Jaya', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1171', 'nama_wilayah' => 'Kota Banda Aceh', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1172', 'nama_wilayah' => 'Kota Sabang', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1173', 'nama_wilayah' => 'Kota Langsa', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1174', 'nama_wilayah' => 'Kota Lhokseumawe', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1175', 'nama_wilayah' => 'Kota Subulussalam', 'kode_prov' => '11', 'created_at' => now(), 'updated_at' => now()],

            // Data Provinsi Sumatera Utara (kode_prov = 12)
            ['kode_area' => '1201', 'nama_wilayah' => 'Kab. Nias', 'kode_prov' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1202', 'nama_wilayah' => 'Kab. Mandailing Natal', 'kode_prov' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1203', 'nama_wilayah' => 'Kab. Tapanuli Selatan', 'kode_prov' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1204', 'nama_wilayah' => 'Kab. Tapanuli Tengah', 'kode_prov' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1205', 'nama_wilayah' => 'Kab. Tapanuli Utara', 'kode_prov' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1206', 'nama_wilayah' => 'Kab. Toba', 'kode_prov' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1207', 'nama_wilayah' => 'Kab. Labuhanbatu', 'kode_prov' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1208', 'nama_wilayah' => 'Kab. Asahan', 'kode_prov' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1209', 'nama_wilayah' => 'Kab. Simalungun', 'kode_prov' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1210', 'nama_wilayah' => 'Kab. Dairi', 'kode_prov' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1211', 'nama_wilayah' => 'Kab. Karo', 'kode_prov' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1212', 'nama_wilayah' => 'Kab. Deli Serdang', 'kode_prov' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1213', 'nama_wilayah' => 'Kab. Langkat', 'kode_prov' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1271', 'nama_wilayah' => 'Kota Sibolga', 'kode_prov' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1272', 'nama_wilayah' => 'Kota Tanjung Balai', 'kode_prov' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1273', 'nama_wilayah' => 'Kota Pematangsiantar', 'kode_prov' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1274', 'nama_wilayah' => 'Kota Tebing Tinggi', 'kode_prov' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1275', 'nama_wilayah' => 'Kota Medan', 'kode_prov' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1276', 'nama_wilayah' => 'Kota Binjai', 'kode_prov' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1277', 'nama_wilayah' => 'Kota Padang Sidempuan', 'kode_prov' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1278', 'nama_wilayah' => 'Kota Gunungsitoli', 'kode_prov' => '12', 'created_at' => now(), 'updated_at' => now()],

              // Data Provinsi Sumatera Barat (kode_prov = 13)
              ['kode_area' => '1301', 'nama_wilayah' => 'Kab. Kepulauan Mentawai', 'kode_prov' => '13', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '1302', 'nama_wilayah' => 'Kab. Pesisir Selatan', 'kode_prov' => '13', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '1303', 'nama_wilayah' => 'Kab. Solok', 'kode_prov' => '13', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '1304', 'nama_wilayah' => 'Kab. Sijunjung', 'kode_prov' => '13', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '1305', 'nama_wilayah' => 'Kab. Tanah Datar', 'kode_prov' => '13', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '1306', 'nama_wilayah' => 'Kab. Padang Pariaman', 'kode_prov' => '13', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '1307', 'nama_wilayah' => 'Kab. Agam', 'kode_prov' => '13', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '1308', 'nama_wilayah' => 'Kab. Lima Puluh Kota', 'kode_prov' => '13', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '1309', 'nama_wilayah' => 'Kab. Pasaman', 'kode_prov' => '13', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '1310', 'nama_wilayah' => 'Kab. Solok Selatan', 'kode_prov' => '13', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '1311', 'nama_wilayah' => 'Kab. Dharmasraya', 'kode_prov' => '13', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '1312', 'nama_wilayah' => 'Kab. Pasaman Barat', 'kode_prov' => '13', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '1371', 'nama_wilayah' => 'Kota Padang', 'kode_prov' => '13', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '1372', 'nama_wilayah' => 'Kota Solok', 'kode_prov' => '13', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '1373', 'nama_wilayah' => 'Kota Sawahlunto', 'kode_prov' => '13', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '1374', 'nama_wilayah' => 'Kota Padang Panjang', 'kode_prov' => '13', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '1375', 'nama_wilayah' => 'Kota Bukittinggi', 'kode_prov' => '13', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '1376', 'nama_wilayah' => 'Kota Payakumbuh', 'kode_prov' => '13', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '1377', 'nama_wilayah' => 'Kota Pariaman', 'kode_prov' => '13', 'created_at' => now(), 'updated_at' => now()],

                // Data Provinsi Riau (kode_prov = 14)
            ['kode_area' => '1401', 'nama_wilayah' => 'Kab. Kuantan Singingi', 'kode_prov' => '14', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1402', 'nama_wilayah' => 'Kab. Indragiri Hulu', 'kode_prov' => '14', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1403', 'nama_wilayah' => 'Kab. Indragiri Hilir', 'kode_prov' => '14', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1404', 'nama_wilayah' => 'Kab. Pelalawan', 'kode_prov' => '14', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1405', 'nama_wilayah' => 'Kab. Siak', 'kode_prov' => '14', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1406', 'nama_wilayah' => 'Kab. Kampar', 'kode_prov' => '14', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1407', 'nama_wilayah' => 'Kab. Rokan Hulu', 'kode_prov' => '14', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1408', 'nama_wilayah' => 'Kab. Bengkalis', 'kode_prov' => '14', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1409', 'nama_wilayah' => 'Kab. Rokan Hilir', 'kode_prov' => '14', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1410', 'nama_wilayah' => 'Kab. Kepulauan Meranti', 'kode_prov' => '14', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1471', 'nama_wilayah' => 'Kota Pekanbaru', 'kode_prov' => '14', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1473', 'nama_wilayah' => 'Kota Dumai', 'kode_prov' => '14', 'created_at' => now(), 'updated_at' => now()],

            // Data Provinsi Jambi (kode_prov = 15)
            ['kode_area' => '1501', 'nama_wilayah' => 'Kab. Kerinci', 'kode_prov' => '15', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1502', 'nama_wilayah' => 'Kab. Merangin', 'kode_prov' => '15', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1503', 'nama_wilayah' => 'Kab. Sarolangun', 'kode_prov' => '15', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1504', 'nama_wilayah' => 'Kab. Batanghari', 'kode_prov' => '15', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1505', 'nama_wilayah' => 'Kab. Muaro Jambi', 'kode_prov' => '15', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1506', 'nama_wilayah' => 'Kab. Tanjung Jabung Timur', 'kode_prov' => '15', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1507', 'nama_wilayah' => 'Kab. Tanjung Jabung Barat', 'kode_prov' => '15', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1508', 'nama_wilayah' => 'Kab. Tebo', 'kode_prov' => '15', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1509', 'nama_wilayah' => 'Kab. Bungo', 'kode_prov' => '15', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1571', 'nama_wilayah' => 'Kota Jambi', 'kode_prov' => '15', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1572', 'nama_wilayah' => 'Kota Sungai Penuh', 'kode_prov' => '15', 'created_at' => now(), 'updated_at' => now()],

             // Data Provinsi Sumatera Selatan (kode_prov = 16)
             ['kode_area' => '1601', 'nama_wilayah' => 'Kab. Ogan Komering Ulu', 'kode_prov' => '16', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1602', 'nama_wilayah' => 'Kab. Ogan Komering Ilir', 'kode_prov' => '16', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1603', 'nama_wilayah' => 'Kab. Muara Enim', 'kode_prov' => '16', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1604', 'nama_wilayah' => 'Kab. Lahat', 'kode_prov' => '16', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1605', 'nama_wilayah' => 'Kab. Musi Rawas', 'kode_prov' => '16', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1606', 'nama_wilayah' => 'Kab. Musi Banyuasin', 'kode_prov' => '16', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1607', 'nama_wilayah' => 'Kab. Banyuasin', 'kode_prov' => '16', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1671', 'nama_wilayah' => 'Kota Palembang', 'kode_prov' => '16', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1672', 'nama_wilayah' => 'Kota Prabumulih', 'kode_prov' => '16', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1673', 'nama_wilayah' => 'Kota Pagar Alam', 'kode_prov' => '16', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1674', 'nama_wilayah' => 'Kota Lubuk Linggau', 'kode_prov' => '16', 'created_at' => now(), 'updated_at' => now()],

              // Data Provinsi Bengkulu (kode_prov = 17)
            ['kode_area' => '1701', 'nama_wilayah' => 'Kab. Bengkulu Selatan', 'kode_prov' => '17', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1702', 'nama_wilayah' => 'Kab. Rejang Lebong', 'kode_prov' => '17', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1703', 'nama_wilayah' => 'Kab. Bengkulu Utara', 'kode_prov' => '17', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1704', 'nama_wilayah' => 'Kab. Kaur', 'kode_prov' => '17', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1705', 'nama_wilayah' => 'Kab. Seluma', 'kode_prov' => '17', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1706', 'nama_wilayah' => 'Kab. Muko Muko', 'kode_prov' => '17', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1707', 'nama_wilayah' => 'Kab. Lebong', 'kode_prov' => '17', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1708', 'nama_wilayah' => 'Kab. Kepahiang', 'kode_prov' => '17', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1709', 'nama_wilayah' => 'Kab. Bengkulu Tengah', 'kode_prov' => '17', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1771', 'nama_wilayah' => 'Kota Bengkulu', 'kode_prov' => '17', 'created_at' => now(), 'updated_at' => now()],

             // Data Provinsi Lampung (kode_prov = 18)
             ['kode_area' => '1801', 'nama_wilayah' => 'Kab. Lampung Barat', 'kode_prov' => '18', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1802', 'nama_wilayah' => 'Kab. Tanggamus', 'kode_prov' => '18', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1803', 'nama_wilayah' => 'Kab. Lampung Selatan', 'kode_prov' => '18', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1804', 'nama_wilayah' => 'Kab. Lampung Timur', 'kode_prov' => '18', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1805', 'nama_wilayah' => 'Kab. Lampung Tengah', 'kode_prov' => '18', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1806', 'nama_wilayah' => 'Kab. Lampung Utara', 'kode_prov' => '18', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1807', 'nama_wilayah' => 'Kab. Way Kanan', 'kode_prov' => '18', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1808', 'nama_wilayah' => 'Kab. Tulang Bawang', 'kode_prov' => '18', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1809', 'nama_wilayah' => 'Kab. Pesawaran', 'kode_prov' => '18', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1810', 'nama_wilayah' => 'Kab. Pringsewu', 'kode_prov' => '18', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1811', 'nama_wilayah' => 'Kab. Mesuji', 'kode_prov' => '18', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1812', 'nama_wilayah' => 'Kab. Tulang Bawang Barat', 'kode_prov' => '18', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1813', 'nama_wilayah' => 'Kab. Pesisir Barat', 'kode_prov' => '18', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1871', 'nama_wilayah' => 'Kota Bandar Lampung', 'kode_prov' => '18', 'created_at' => now(), 'updated_at' => now()],
             ['kode_area' => '1872', 'nama_wilayah' => 'Kota Metro', 'kode_prov' => '18', 'created_at' => now(), 'updated_at' => now()],

               // Data Provinsi Kepulauan Bangka Belitung (kode_prov = 19)
            ['kode_area' => '1901', 'nama_wilayah' => 'Kab. Bangka', 'kode_prov' => '19', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1902', 'nama_wilayah' => 'Kab. Belitung', 'kode_prov' => '19', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1903', 'nama_wilayah' => 'Kab. Bangka Barat', 'kode_prov' => '19', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1904', 'nama_wilayah' => 'Kab. Bangka Tengah', 'kode_prov' => '19', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1905', 'nama_wilayah' => 'Kab. Bangka Selatan', 'kode_prov' => '19', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1906', 'nama_wilayah' => 'Kab. Belitung Timur', 'kode_prov' => '19', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '1971', 'nama_wilayah' => 'Kota Pangkal Pinang', 'kode_prov' => '19', 'created_at' => now(), 'updated_at' => now()],


              // Data Provinsi Kepulauan Riau (kode_prov = 21)
              ['kode_area' => '2101', 'nama_wilayah' => 'Kab. Karimun', 'kode_prov' => '21', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '2102', 'nama_wilayah' => 'Kab. Bintan', 'kode_prov' => '21', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '2103', 'nama_wilayah' => 'Kab. Natuna', 'kode_prov' => '21', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '2104', 'nama_wilayah' => 'Kab. Lingga', 'kode_prov' => '21', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '2105', 'nama_wilayah' => 'Kab. Kepulauan Anambas', 'kode_prov' => '21', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '2171', 'nama_wilayah' => 'Kota Batam', 'kode_prov' => '21', 'created_at' => now(), 'updated_at' => now()],
              ['kode_area' => '2172', 'nama_wilayah' => 'Kota Tanjung Pinang', 'kode_prov' => '21', 'created_at' => now(), 'updated_at' => now()],

               // Data Provinsi DKI Jakarta (kode_prov = 31)
            ['kode_area' => '3101', 'nama_wilayah' => 'Kab. Adm. Kep. Seribu', 'kode_prov' => '31', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3171', 'nama_wilayah' => 'Kota Adm. Jakarta Selatan', 'kode_prov' => '31', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3172', 'nama_wilayah' => 'Kota Adm. Jakarta Timur', 'kode_prov' => '31', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3173', 'nama_wilayah' => 'Kota Adm. Jakarta Pusat', 'kode_prov' => '31', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3174', 'nama_wilayah' => 'Kota Adm. Jakarta Barat', 'kode_prov' => '31', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3175', 'nama_wilayah' => 'Kota Adm. Jakarta Utara', 'kode_prov' => '31', 'created_at' => now(), 'updated_at' => now()],


            //data provinsi jawa barat (kode_prov = 32)
            ['kode_area' => '3201', 'nama_wilayah' => 'Kab. Bogor', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3202', 'nama_wilayah' => 'Kab. Sukabumi', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3203', 'nama_wilayah' => 'Kab. Cianjur', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3204', 'nama_wilayah' => 'Kab. Bandung', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3205', 'nama_wilayah' => 'Kab. Garut', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3206', 'nama_wilayah' => 'Kab. Tasikmalaya', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3207', 'nama_wilayah' => 'Kab. Ciamis', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3208', 'nama_wilayah' => 'Kab. Kuningan', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3209', 'nama_wilayah' => 'Kab. Cirebon', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3210', 'nama_wilayah' => 'Kab. Majalengka', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3211', 'nama_wilayah' => 'Kab. Sumedang', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3212', 'nama_wilayah' => 'Kab. Indramayu', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3213', 'nama_wilayah' => 'Kab. Subang', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3214', 'nama_wilayah' => 'Kab. Purwakarta', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3215', 'nama_wilayah' => 'Kab. Karawang', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3216', 'nama_wilayah' => 'Kab. Bekasi', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3217', 'nama_wilayah' => 'Kab. Bandung Barat', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3218', 'nama_wilayah' => 'Kab. Pangandaran', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3271', 'nama_wilayah' => 'Kota Bogor', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3272', 'nama_wilayah' => 'Kota Sukabumi', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3273', 'nama_wilayah' => 'Kota Bandung', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3274', 'nama_wilayah' => 'Kota Cirebon', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3275', 'nama_wilayah' => 'Kota Bekasi', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3276', 'nama_wilayah' => 'Kota Depok', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3277', 'nama_wilayah' => 'Kota Cimahi', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3278', 'nama_wilayah' => 'Kota Tasikmalaya', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3279', 'nama_wilayah' => 'Kota Banjar', 'kode_prov' => '32', 'created_at' => now(), 'updated_at' => now()],


            //data provinsi jawa tengah
            ['kode_area' => '3301', 'nama_wilayah' => 'Kab. Cilacap', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3302', 'nama_wilayah' => 'Kab. Banyumas', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3303', 'nama_wilayah' => 'Kab. Purbalingga', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3304', 'nama_wilayah' => 'Kab. Banjarnegara', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3305', 'nama_wilayah' => 'Kab. Kebumen', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3306', 'nama_wilayah' => 'Kab. Purworejo', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3307', 'nama_wilayah' => 'Kab. Wonosobo', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3308', 'nama_wilayah' => 'Kab. Magelang', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3309', 'nama_wilayah' => 'Kab. Boyolali', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3310', 'nama_wilayah' => 'Kab. Klaten', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3311', 'nama_wilayah' => 'Kab. Sukoharjo', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3312', 'nama_wilayah' => 'Kab. Wonogiri', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3313', 'nama_wilayah' => 'Kab. Karanganyar', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3314', 'nama_wilayah' => 'Kab. Sragen', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3315', 'nama_wilayah' => 'Kab. Grobogan', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3316', 'nama_wilayah' => 'Kab. Blora', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3317', 'nama_wilayah' => 'Kab. Rembang', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3318', 'nama_wilayah' => 'Kab. Pati', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3319', 'nama_wilayah' => 'Kab. Kudus', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3320', 'nama_wilayah' => 'Kab. Jepara', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3321', 'nama_wilayah' => 'Kab. Demak', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3322', 'nama_wilayah' => 'Kab. Semarang', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3323', 'nama_wilayah' => 'Kab. Temanggung', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3324', 'nama_wilayah' => 'Kab. Kendal', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3325', 'nama_wilayah' => 'Kab. Batang', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3326', 'nama_wilayah' => 'Kab. Pekalongan', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3327', 'nama_wilayah' => 'Kab. Pemalang', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3328', 'nama_wilayah' => 'Kab. Tegal', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3329', 'nama_wilayah' => 'Kab. Brebes', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3371', 'nama_wilayah' => 'Kota Magelang', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3372', 'nama_wilayah' => 'Kota Surakarta', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3373', 'nama_wilayah' => 'Kota Salatiga', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3374', 'nama_wilayah' => 'Kota Semarang', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3375', 'nama_wilayah' => 'Kota Pekalongan', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3376', 'nama_wilayah' => 'Kota Tegal', 'kode_prov' => '33', 'created_at' => now(), 'updated_at' => now()],

             // Data untuk Provinsi 34 (DI Yogyakarta)
            ['kode_area' => '3401', 'nama_wilayah' => 'Kab. Kulon Progo', 'kode_prov' => '34', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3402', 'nama_wilayah' => 'Kab. Bantul', 'kode_prov' => '34', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3403', 'nama_wilayah' => 'Kab. Gunungkidul', 'kode_prov' => '34', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3404', 'nama_wilayah' => 'Kab. Sleman', 'kode_prov' => '34', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3471', 'nama_wilayah' => 'Kota Yogyakarta', 'kode_prov' => '34', 'created_at' => now(), 'updated_at' => now()],

            //data provinsi jawa timur 35
            ['kode_area' => '3501', 'nama_wilayah' => 'Kab. Pacitan', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3502', 'nama_wilayah' => 'Kab. Ponorogo', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3503', 'nama_wilayah' => 'Kab. Trenggalek', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3504', 'nama_wilayah' => 'Kab. Tulungagung', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3505', 'nama_wilayah' => 'Kab. Blitar', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3506', 'nama_wilayah' => 'Kab. Kediri', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3507', 'nama_wilayah' => 'Kab. Malang', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3508', 'nama_wilayah' => 'Kab. Lumajang', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3509', 'nama_wilayah' => 'Kab. Jember', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3510', 'nama_wilayah' => 'Kab. Banyuwangi', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3511', 'nama_wilayah' => 'Kab. Bondowoso', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3512', 'nama_wilayah' => 'Kab. Situbondo', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3513', 'nama_wilayah' => 'Kab. Probolinggo', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3514', 'nama_wilayah' => 'Kab. Pasuruan', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3515', 'nama_wilayah' => 'Kab. Sidoarjo', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3516', 'nama_wilayah' => 'Kab. Mojokerto', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3517', 'nama_wilayah' => 'Kab. Jombang', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3518', 'nama_wilayah' => 'Kab. Nganjuk', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3519', 'nama_wilayah' => 'Kab. Madiun', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3520', 'nama_wilayah' => 'Kab. Magetan', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3521', 'nama_wilayah' => 'Kab. Ngawi', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3522', 'nama_wilayah' => 'Kab. Bojonegoro', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3523', 'nama_wilayah' => 'Kab. Tuban', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3524', 'nama_wilayah' => 'Kab. Lamongan', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3525', 'nama_wilayah' => 'Kab. Gresik', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3526', 'nama_wilayah' => 'Kab. Bangkalan', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3527', 'nama_wilayah' => 'Kab. Sampang', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3528', 'nama_wilayah' => 'Kab. Pamekasan', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3529', 'nama_wilayah' => 'Kab. Sumenep', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3571', 'nama_wilayah' => 'Kota Kediri', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3572', 'nama_wilayah' => 'Kota Blitar', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3573', 'nama_wilayah' => 'Kota Malang', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3574', 'nama_wilayah' => 'Kota Probolinggo', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3575', 'nama_wilayah' => 'Kota Pasuruan', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3576', 'nama_wilayah' => 'Kota Mojokerto', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3577', 'nama_wilayah' => 'Kota Madiun', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3578', 'nama_wilayah' => 'Kota Surabaya', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3579', 'nama_wilayah' => 'Kota Batu', 'kode_prov' => '35', 'created_at' => now(), 'updated_at' => now()],

             // Data provinsi banten dengan kode 36
            ['kode_area' => '3601', 'nama_wilayah' => 'Kab. Pandeglang', 'kode_prov' => '36', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3602', 'nama_wilayah' => 'Kab. Lebak', 'kode_prov' => '36', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3603', 'nama_wilayah' => 'Kab. Tangerang', 'kode_prov' => '36', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3604', 'nama_wilayah' => 'Kab. Serang', 'kode_prov' => '36', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3671', 'nama_wilayah' => 'Kota Tangerang', 'kode_prov' => '36', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3672', 'nama_wilayah' => 'Kota Cilegon', 'kode_prov' => '36', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3673', 'nama_wilayah' => 'Kota Serang', 'kode_prov' => '36', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '3674', 'nama_wilayah' => 'Kota Tangerang Selatan', 'kode_prov' => '36', 'created_at' => now(), 'updated_at' => now()],

            // Data provinsi bali dengan kode 51
            ['kode_area' => '5101', 'nama_wilayah' => 'Kab. Jembrana', 'kode_prov' => '51', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5102', 'nama_wilayah' => 'Kab. Tabanan', 'kode_prov' => '51', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5103', 'nama_wilayah' => 'Kab. Badung', 'kode_prov' => '51', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5104', 'nama_wilayah' => 'Kab. Gianyar', 'kode_prov' => '51', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5105', 'nama_wilayah' => 'Kab. Klungkung', 'kode_prov' => '51', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5106', 'nama_wilayah' => 'Kab. Bangli', 'kode_prov' => '51', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5107', 'nama_wilayah' => 'Kab. Karangasem', 'kode_prov' => '51', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5108', 'nama_wilayah' => 'Kab. Buleleng', 'kode_prov' => '51', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5171', 'nama_wilayah' => 'Kota Denpasar', 'kode_prov' => '51', 'created_at' => now(), 'updated_at' => now()],

            //data provinsi nusa tenggara barat dengan kode 52
            ['kode_area' => '5201', 'nama_wilayah' => 'Kab. Lombok Barat', 'kode_prov' => '52', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5202', 'nama_wilayah' => 'Kab. Lombok Tengah', 'kode_prov' => '52', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5203', 'nama_wilayah' => 'Kab. Lombok Timur', 'kode_prov' => '52', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5204', 'nama_wilayah' => 'Kab. Sumbawa', 'kode_prov' => '52', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5205', 'nama_wilayah' => 'Kab. Dompu', 'kode_prov' => '52', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5206', 'nama_wilayah' => 'Kab. Bima', 'kode_prov' => '52', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5207', 'nama_wilayah' => 'Kab. Sumbawa Barat', 'kode_prov' => '52', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5208', 'nama_wilayah' => 'Kab. Lombok Utara', 'kode_prov' => '52', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5271', 'nama_wilayah' => 'Kota Mataram', 'kode_prov' => '52', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5272', 'nama_wilayah' => 'Kota Bima', 'kode_prov' => '52', 'created_at' => now(), 'updated_at' => now()],

            //data provinsi nusa tenggara timur dengan kode 53
            ['kode_area' => '5301', 'nama_wilayah' => 'Kab. Sumba Barat', 'kode_prov' => '53', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5302', 'nama_wilayah' => 'Kab. Sumba Timur', 'kode_prov' => '53', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5303', 'nama_wilayah' => 'Kab. Kupang', 'kode_prov' => '53', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5304', 'nama_wilayah' => 'Kab Timor Tengah Selatan', 'kode_prov' => '53', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5305', 'nama_wilayah' => 'Kab. Timor Tengah Utara', 'kode_prov' => '53', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5306', 'nama_wilayah' => 'Kab. Belu', 'kode_prov' => '53', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5307', 'nama_wilayah' => 'Kab. Alor', 'kode_prov' => '53', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5308', 'nama_wilayah' => 'Kab. Lembata', 'kode_prov' => '53', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5309', 'nama_wilayah' => 'Kab. Flores Timur', 'kode_prov' => '53', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5310', 'nama_wilayah' => 'Kab. Sikka', 'kode_prov' => '53', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5311', 'nama_wilayah' => 'Kab. Ende', 'kode_prov' => '53', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5312', 'nama_wilayah' => 'Kab. Ngada', 'kode_prov' => '53', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5313', 'nama_wilayah' => 'Kab. Manggarai', 'kode_prov' => '53', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5314', 'nama_wilayah' => 'Kab. Rote Ndao', 'kode_prov' => '53', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '5371', 'nama_wilayah' => 'Kota Kupang', 'kode_prov' => '53', 'created_at' => now(), 'updated_at' => now()],

            //data provinsi kalimantan barat dengan kode 61
            ['kode_area' => '6101', 'nama_wilayah' => 'Kab. Sambas', 'kode_prov' => '61', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6102', 'nama_wilayah' => 'Kab. Bengkayang', 'kode_prov' => '61', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6103', 'nama_wilayah' => 'Kab. Landak', 'kode_prov' => '61', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6104', 'nama_wilayah' => 'Kab. Mempawah', 'kode_prov' => '61', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6105', 'nama_wilayah' => 'Kab. Sanggau', 'kode_prov' => '61', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6171', 'nama_wilayah' => 'Kota Pontianak', 'kode_prov' => '61', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6172', 'nama_wilayah' => 'Kota Singkawang', 'kode_prov' => '61', 'created_at' => now(), 'updated_at' => now()],

            //data provinsi kalimantan tengah dengan kode 62
            ['kode_area' => '6201', 'nama_wilayah' => 'Kab. Kotawaringin Barat',  'kode_prov' => '62', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6202', 'nama_wilayah' => 'Kab. Kotawaringin Timur',  'kode_prov' => '62', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6203', 'nama_wilayah' => 'Kab. Kapuas',             'kode_prov' => '62', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6204', 'nama_wilayah' => 'Kab. Barito Selatan',     'kode_prov' => '62', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6205', 'nama_wilayah' => 'Kab. Barito Utara',       'kode_prov' => '62', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6206', 'nama_wilayah' => 'Kab. Sukamara',           'kode_prov' => '62', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6207', 'nama_wilayah' => 'Kab. Lamandau',           'kode_prov' => '62', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6208', 'nama_wilayah' => 'Kab. Seruyan',            'kode_prov' => '62', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6209', 'nama_wilayah' => 'Kab. Katingan',           'kode_prov' => '62', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6210', 'nama_wilayah' => 'Kab. Pulang Pisau',       'kode_prov' => '62', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6211', 'nama_wilayah' => 'Kab. Gunung Mas',         'kode_prov' => '62', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6212', 'nama_wilayah' => 'Kab. Barito Timur',       'kode_prov' => '62', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6213', 'nama_wilayah' => 'Kab. Murung Raya',        'kode_prov' => '62', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6271', 'nama_wilayah' => 'Kota Palangkaraya',       'kode_prov' => '62', 'created_at' => now(), 'updated_at' => now()],

            //data provinsi kalimantan selatan dengan kode 63
            ['kode_area' => '6301', 'nama_wilayah' => 'Kab. Tanah Laut',         'kode_prov' => '63', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6302', 'nama_wilayah' => 'Kab. Kota Baru',          'kode_prov' => '63', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6303', 'nama_wilayah' => 'Kab. Banjar',             'kode_prov' => '63', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6304', 'nama_wilayah' => 'Kab. Barito Kuala',       'kode_prov' => '63', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6305', 'nama_wilayah' => 'Kab. Tapin',              'kode_prov' => '63', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6306', 'nama_wilayah' => 'Kab. Hulu Sungai Selatan','kode_prov' => '63', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6307', 'nama_wilayah' => 'Kab. Hulu Sungai Tengah', 'kode_prov' => '63', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6308', 'nama_wilayah' => 'Kab. Hulu Sungai Utara',  'kode_prov' => '63', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6309', 'nama_wilayah' => 'Kab. Tabalong',           'kode_prov' => '63', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6310', 'nama_wilayah' => 'Kab. Tanah Bumbu',        'kode_prov' => '63', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6311', 'nama_wilayah' => 'Kab. Balangan',           'kode_prov' => '63', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6371', 'nama_wilayah' => 'Kota Banjarmasin',        'kode_prov' => '63', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6372', 'nama_wilayah' => 'Kota Banjarbaru',         'kode_prov' => '63', 'created_at' => now(), 'updated_at' => now()],

            //data kalimantan timur dengan kode 64
            ['kode_area' => '6401', 'nama_wilayah' => 'Kab. Paser',              'kode_prov' => '64', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6402', 'nama_wilayah' => 'Kab. Kutai Barat',       'kode_prov' => '64', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6403', 'nama_wilayah' => 'Kab. Kutai Kartanegara', 'kode_prov' => '64', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6404', 'nama_wilayah' => 'Kab. Kutai Timur',       'kode_prov' => '64', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6405', 'nama_wilayah' => 'Kab. Berau',             'kode_prov' => '64', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6409', 'nama_wilayah' => 'Kab. Penajam Paser Utara','kode_prov' => '64', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6411', 'nama_wilayah' => 'Kab. Mahakam Ulu',       'kode_prov' => '64', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6471', 'nama_wilayah' => 'Kota Balikpapan',        'kode_prov' => '64', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6472', 'nama_wilayah' => 'Kota Samarinda',         'kode_prov' => '64', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6473', 'nama_wilayah' => 'Kota Bontang',           'kode_prov' => '64', 'created_at' => now(), 'updated_at' => now()],

            //data kalimantan utara dengan kode 65
            ['kode_area' => '6501', 'nama_wilayah' => 'Kab. Malinau',           'kode_prov' => '65', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6502', 'nama_wilayah' => 'Kab. Bulungan',         'kode_prov' => '65', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6503', 'nama_wilayah' => 'Kab. Tana Tidung',      'kode_prov' => '65', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6504', 'nama_wilayah' => 'Kab. Nunukan',          'kode_prov' => '65', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '6571', 'nama_wilayah' => 'Kota Tarakan',          'kode_prov' => '65', 'created_at' => now(), 'updated_at' => now()],

            //data sulawesi utara dengan kode 71
            ['kode_area' => '7101', 'nama_wilayah' => 'Kab. Kepulauan Sangihe',  'kode_prov' => '71', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7102', 'nama_wilayah' => 'Kab. Kepulauan Talaud',   'kode_prov' => '71', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7103', 'nama_wilayah' => 'Kab. Minahasa',           'kode_prov' => '71', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7104', 'nama_wilayah' => 'Kab. Minahasa Selatan',   'kode_prov' => '71', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7105', 'nama_wilayah' => 'Kab. Minahasa Tenggara',  'kode_prov' => '71', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7106', 'nama_wilayah' => 'Kab. Minahasa Utara',     'kode_prov' => '71', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7107', 'nama_wilayah' => 'Kab. Bolaang Mongondow',  'kode_prov' => '71', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7108', 'nama_wilayah' => 'Kab. Bolaang Mongondow Utara', 'kode_prov' => '71', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7109', 'nama_wilayah' => 'Kab. Bolaang Mongondow Selatan', 'kode_prov' => '71', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7110', 'nama_wilayah' => 'Kab. Bolaang Mongondow Timur', 'kode_prov' => '71', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7171', 'nama_wilayah' => 'Kota Manado',            'kode_prov' => '71', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7172', 'nama_wilayah' => 'Kota Bitung',            'kode_prov' => '71', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7173', 'nama_wilayah' => 'Kota Tomohon',           'kode_prov' => '71', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7174', 'nama_wilayah' => 'Kota Kotamobagu',        'kode_prov' => '71', 'created_at' => now(), 'updated_at' => now()],

            //data sulawesi tengah dengan kode 72
            ['kode_area' => '7201', 'nama_wilayah' => 'Kab. Banggai',            'kode_prov' => '72', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7202', 'nama_wilayah' => 'Kab. Banggai Kepulauan', 'kode_prov' => '72', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7203', 'nama_wilayah' => 'Kab. Banggai Laut',      'kode_prov' => '72', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7204', 'nama_wilayah' => 'Kab. Morowali',          'kode_prov' => '72', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7205', 'nama_wilayah' => 'Kab. Morowali Utara',    'kode_prov' => '72', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7206', 'nama_wilayah' => 'Kab. Poso',              'kode_prov' => '72', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7207', 'nama_wilayah' => 'Kab. Donggala',          'kode_prov' => '72', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7208', 'nama_wilayah' => 'Kab. Tolitoli',          'kode_prov' => '72', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7209', 'nama_wilayah' => 'Kab. Buol',              'kode_prov' => '72', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7210', 'nama_wilayah' => 'Kab. Parigi Moutong',    'kode_prov' => '72', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7211', 'nama_wilayah' => 'Kab. Tojo Una-Una',      'kode_prov' => '72', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7212', 'nama_wilayah' => 'Kab. Sigi',              'kode_prov' => '72', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7271', 'nama_wilayah' => 'Kota Palu',              'kode_prov' => '72', 'created_at' => now(), 'updated_at' => now()],

            //data sulawesi selatan dengan kode 73
            ['kode_area' => '7301', 'nama_wilayah' => 'Kab. Kepulauan Selayar', 'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7302', 'nama_wilayah' => 'Kab. Bulukumba',        'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7303', 'nama_wilayah' => 'Kab. Bantaeng',         'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7304', 'nama_wilayah' => 'Kab. Jeneponto',        'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7305', 'nama_wilayah' => 'Kab. Takalar',          'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7306', 'nama_wilayah' => 'Kab. Gowa',             'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7307', 'nama_wilayah' => 'Kab. Sinjai',           'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7308', 'nama_wilayah' => 'Kab. Maros',            'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7309', 'nama_wilayah' => 'Kab. Pangkajene Kepulauan', 'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7310', 'nama_wilayah' => 'Kab. Barru',            'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7311', 'nama_wilayah' => 'Kab. Bone',             'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7312', 'nama_wilayah' => 'Kab. Soppeng',          'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7313', 'nama_wilayah' => 'Kab. Wajo',             'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7314', 'nama_wilayah' => 'Kab. Sidrap',           'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7315', 'nama_wilayah' => 'Kab. Pinrang',          'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7316', 'nama_wilayah' => 'Kab. Enrekang',         'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7317', 'nama_wilayah' => 'Kab. Luwu',             'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7318', 'nama_wilayah' => 'Kab. Tana Toraja',      'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7322', 'nama_wilayah' => 'Kab. Luwu Utara',       'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7325', 'nama_wilayah' => 'Kab. Luwu Timur',       'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7326', 'nama_wilayah' => 'Kab. Toraja Utara',     'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7371', 'nama_wilayah' => 'Kota Makassar',         'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7372', 'nama_wilayah' => 'Kota Parepare',         'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7373', 'nama_wilayah' => 'Kota Palopo',           'kode_prov' => '73', 'created_at' => now(), 'updated_at' => now()],

            //data sulawesi tenggara dengan kode 74
            ['kode_area' => '7401', 'nama_wilayah' => 'Kab. Buton',            'kode_prov' => '74', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7402', 'nama_wilayah' => 'Kab. Muna',             'kode_prov' => '74', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7403', 'nama_wilayah' => 'Kab. Konawe',           'kode_prov' => '74', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7404', 'nama_wilayah' => 'Kab. Kolaka',           'kode_prov' => '74', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7405', 'nama_wilayah' => 'Kab. Konawe Selatan',   'kode_prov' => '74', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7406', 'nama_wilayah' => 'Kab. Bombana',          'kode_prov' => '74', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7407', 'nama_wilayah' => 'Kab. Wakatobi',         'kode_prov' => '74', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7408', 'nama_wilayah' => 'Kab. Kolaka Utara',     'kode_prov' => '74', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7409', 'nama_wilayah' => 'Kab. Konawe Utara',     'kode_prov' => '74', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7410', 'nama_wilayah' => 'Kab. Buton Utara',      'kode_prov' => '74', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7411', 'nama_wilayah' => 'Kab. Kolaka Timur',     'kode_prov' => '74', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7412', 'nama_wilayah' => 'Kab. Konawe Kepulauan', 'kode_prov' => '74', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7413', 'nama_wilayah' => 'Kab. Muna Barat',       'kode_prov' => '74', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7414', 'nama_wilayah' => 'Kab. Buton Tengah',     'kode_prov' => '74', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7415', 'nama_wilayah' => 'Kab. Buton Selatan',    'kode_prov' => '74', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7471', 'nama_wilayah' => 'Kota Kendari',          'kode_prov' => '74', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7472', 'nama_wilayah' => 'Kota Baubau',           'kode_prov' => '74', 'created_at' => now(), 'updated_at' => now()],

            //data gorontalo dengan kode 75
            ['kode_area' => '7501', 'nama_wilayah' => 'Kab. Boalemo',         'kode_prov' => '75', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7502', 'nama_wilayah' => 'Kab. Gorontalo',       'kode_prov' => '75', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7503', 'nama_wilayah' => 'Kab. Pohuwato',        'kode_prov' => '75', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7504', 'nama_wilayah' => 'Kab. Bone Bolango',    'kode_prov' => '75', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7505', 'nama_wilayah' => 'Kab. Gorontalo Utara', 'kode_prov' => '75', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7571', 'nama_wilayah' => 'Kota Gorontalo',       'kode_prov' => '75', 'created_at' => now(), 'updated_at' => now()],

            //data sulawesi barat dengan kode 76
            ['kode_area' => '7601', 'nama_wilayah' => 'Kab. Majene',         'kode_prov' => '76', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7602', 'nama_wilayah' => 'Kab. Polewali Mandar', 'kode_prov' => '76', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7603', 'nama_wilayah' => 'Kab. Mamasa',         'kode_prov' => '76', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7604', 'nama_wilayah' => 'Kab. Mamuju',         'kode_prov' => '76', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7605', 'nama_wilayah' => 'Kab. Mamuju Utara',   'kode_prov' => '76', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '7606', 'nama_wilayah' => 'Kab. Mamuju Tengah',  'kode_prov' => '76', 'created_at' => now(), 'updated_at' => now()],

            //data maluku dengan kode 81
            ['kode_area' => '8101', 'nama_wilayah' => 'Kab. Maluku Tenggara',      'kode_prov' => '81', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '8102', 'nama_wilayah' => 'Kab. Maluku Tengah',        'kode_prov' => '81', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '8103', 'nama_wilayah' => 'Kab. Maluku Tenggara Barat','kode_prov' => '81', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '8104', 'nama_wilayah' => 'Kab. Buru',                 'kode_prov' => '81', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '8105', 'nama_wilayah' => 'Kab. Kepulauan Aru',        'kode_prov' => '81', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '8106', 'nama_wilayah' => 'Kab. Seram Bagian Barat',   'kode_prov' => '81', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '8107', 'nama_wilayah' => 'Kab. Seram Bagian Timur',   'kode_prov' => '81', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '8108', 'nama_wilayah' => 'Kab. Maluku Barat Daya',    'kode_prov' => '81', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '8109', 'nama_wilayah' => 'Kab. Buru Selatan',         'kode_prov' => '81', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '8171', 'nama_wilayah' => 'Kota Ambon',                'kode_prov' => '81', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '8172', 'nama_wilayah' => 'Kota Tual',                 'kode_prov' => '81', 'created_at' => now(), 'updated_at' => now()],

            //data maluku utara dengan kode 82
            ['kode_area' => '8201', 'nama_wilayah' => 'Kab. Halmahera Barat',    'kode_prov' => '82', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '8202', 'nama_wilayah' => 'Kab. Halmahera Tengah',   'kode_prov' => '82', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '8203', 'nama_wilayah' => 'Kab. Halmahera Utara',    'kode_prov' => '82', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '8204', 'nama_wilayah' => 'Kab. Halmahera Selatan',  'kode_prov' => '82', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '8205', 'nama_wilayah' => 'Kab. Halmahera Timur',    'kode_prov' => '82', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '8206', 'nama_wilayah' => 'Kab. Kepulauan Sula',     'kode_prov' => '82', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '8207', 'nama_wilayah' => 'Kab. Pulau Morotai',      'kode_prov' => '82', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '8208', 'nama_wilayah' => 'Kab. Pulau Taliabu',      'kode_prov' => '82', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '8271', 'nama_wilayah' => 'Kota Ternate',            'kode_prov' => '82', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '8272', 'nama_wilayah' => 'Kota Tidore Kepulauan',   'kode_prov' => '82', 'created_at' => now(), 'updated_at' => now()],

            //data papua barat dengan kode 91
            ['kode_area' => '9103', 'nama_wilayah' => 'Kab. Jayapura',        'kode_prov' => '91', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9105', 'nama_wilayah' => 'Kab. Kepulauan Yapen', 'kode_prov' => '91', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9106', 'nama_wilayah' => 'Kab. Biak Numfor',     'kode_prov' => '91', 'created_at' => now(), 'updated_at' => now()],

            //data papua barat daya dengan kode 92
            ['kode_area' => '9201', 'nama_wilayah' => 'Kab. Fakfak',           'kode_prov' => '92', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9202', 'nama_wilayah' => 'Kab. Kaimana',         'kode_prov' => '92', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9203', 'nama_wilayah' => 'Kab. Teluk Wondama',   'kode_prov' => '92', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9204', 'nama_wilayah' => 'Kab. Teluk Bintuni',   'kode_prov' => '92', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9205', 'nama_wilayah' => 'Kab. Manokwari',       'kode_prov' => '92', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9206', 'nama_wilayah' => 'Kab. Sorong Selatan',  'kode_prov' => '92', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9207', 'nama_wilayah' => 'Kab. Sorong',          'kode_prov' => '92', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9208', 'nama_wilayah' => 'Kab. Raja Ampat',      'kode_prov' => '92', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9209', 'nama_wilayah' => 'Kab. Tambrauw',        'kode_prov' => '92', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9210', 'nama_wilayah' => 'Kab. Maybrat',         'kode_prov' => '92', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9271', 'nama_wilayah' => 'Kota Sorong',          'kode_prov' => '92', 'created_at' => now(), 'updated_at' => now()],

            //data papua dengan kode 94
            ['kode_area' => '9405', 'nama_wilayah' => 'Kab. Mamberamo Raya',   'kode_prov' => '94', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9411', 'nama_wilayah' => 'Kab. Waropen',          'kode_prov' => '94', 'created_at' => now(), 'updated_at' => now()],

            //data papua selatan dengan kode 95
            ['kode_area' => '9501', 'nama_wilayah' => 'Kab. Merauke', 'kode_prov' => '95', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9502', 'nama_wilayah' => 'Kab. Boven digoel', 'kode_prov' => '95', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9503', 'nama_wilayah' => 'Kab. Mappi', 'kode_prov' => '95', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9504', 'nama_wilayah' => 'Kab. Asmat', 'kode_prov' => '95', 'created_at' => now(), 'updated_at' => now()],


            //data papua tengah dengan kode 96
            ['kode_area' => '9601', 'nama_wilayah' => 'Kab. Mimika',       'kode_prov' => '96', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9602', 'nama_wilayah' => 'Kab. Dogiyai',       'kode_prov' => '96', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9603', 'nama_wilayah' => 'Kab. Deiyai',        'kode_prov' => '96', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9604', 'nama_wilayah' => 'Kab. Nabire',     'kode_prov' => '96', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9605', 'nama_wilayah' => 'Kab. Paniai',     'kode_prov' => '96', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9606', 'nama_wilayah' => 'Kab. Intan jaya',     'kode_prov' => '96', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9607', 'nama_wilayah' => 'Kab. Puncak',      'kode_prov' => '96', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9608', 'nama_wilayah' => 'Kab. Puncak jaya',    'kode_prov' => '96', 'created_at' => now(), 'updated_at' => now()],

            //data papua pegunungan dengan kode 97
            ['kode_area' => '9701', 'nama_wilayah' => 'Kab. Nduga',       'kode_prov' => '97', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9702', 'nama_wilayah' => 'Kab. Jayawijaya',       'kode_prov' => '97', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9703', 'nama_wilayah' => 'Kab. Lanny jaya',       'kode_prov' => '97', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9704', 'nama_wilayah' => 'Kab. Tolikara',       'kode_prov' => '97', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9705', 'nama_wilayah' => 'Kab. Mamberamo tengah',       'kode_prov' => '97', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9706', 'nama_wilayah' => 'Kab. Yalimo',       'kode_prov' => '97', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9707', 'nama_wilayah' => 'Kab. Yahukimo',       'kode_prov' => '97', 'created_at' => now(), 'updated_at' => now()],
            ['kode_area' => '9708', 'nama_wilayah' => 'Kab. Pegunungan bintang',       'kode_prov' => '97', 'created_at' => now(), 'updated_at' => now()],






        ]);

    }
}
